//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicCollection
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicDisk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MusicDisk()
        {
            this.Songs = new HashSet<Songs>();
            this.Styles = new HashSet<Styles>();
        }
    
        public int Id { get; set; }
        public string NameDisk { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int ExecutorId { get; set; }
        public int PublisherId { get; set; }
    
        public virtual Executors Executors { get; set; }
        public virtual Publishers Publishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Songs> Songs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Styles> Styles { get; set; }
    }
}
